# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - dscdsd-site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_e48d7903305547b8b09aa89be22f1b44 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_96846d43d8a3439f813e7550cf58772d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e48d7903305547b8b09aa89be22f1b44 }}/vikopenaisite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'dscdsd-site'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_578c212e7f934b8f9e102a597483ad0a }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_e48d7903305547b8b09aa89be22f1b44 }}/vikopenaisite:${{ github.sha }}'